/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Klient;

import java.awt.Color;
import java.net.InetAddress;
import java.net.UnknownHostException;


/**
 *
 * @author chris
 */
public class Velkomstskærm extends javax.swing.JPanel {

    private KlientFunk klient;
    public int start = 0;
    private String navn;
    private int port;
    private String IP;
    public boolean server_started = false;
    private final short MAX_NAME_LENGTH = 38;
    

    /**
     * Creates new form Velkomstskærm
     */
    public Velkomstskærm() {
        initComponents();
        
        /**/
        String IP = "Kunne ikke få din IP";;
        try {
            IP = InetAddress.getLocalHost().getHostAddress();
            JLabel_Din_ip.setForeground(Color.BLACK);
            //throw new UnknownHostException();
        } catch (UnknownHostException ex) {
            IP = "kunne ikke finde din IP-adresse";
            JLabel_Din_ip.setForeground(Color.red);
        }finally{
            if(IP.matches("127.0.0.1")){
               IP = "der er noget galt med dit netværksinterface. Tjek at du har internet!";
               JLabel_Din_ip.setForeground(Color.red);        
            }
            JLabel_Din_ip.setText("Din IP-adresse: "+IP);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_ip = new javax.swing.JTextField();
        jButton_connect = new javax.swing.JButton();
        jTextField_port = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_navn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton_Opretserver = new javax.swing.JButton();
        jSlider_value = new javax.swing.JSlider();
        jSpinner_antal_spillere = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLabel_Din_ip = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Velkommen til terningespillet Snyd!");

        jTextField_ip.setText("127.0.0.1");
        jTextField_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ipActionPerformed(evt);
            }
        });

        jButton_connect.setText("Connect");
        jButton_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_connectActionPerformed(evt);
            }
        });

        jTextField_port.setText("9000");
        jTextField_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_portActionPerformed(evt);
            }
        });
        jTextField_port.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_portKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_portKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_portKeyReleased(evt);
            }
        });

        jLabel2.setText("IP");

        jLabel3.setText("Port");

        jLabel5.setText("Spillernavn");

        jTextField_navn.setText("Navn");
        jTextField_navn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_navnActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Klient/dice2.png"))); // NOI18N

        jButton_Opretserver.setText("Opret server med angivet port");
        jButton_Opretserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OpretserverActionPerformed(evt);
            }
        });

        jSlider_value.setMajorTickSpacing(1);
        jSlider_value.setMaximum(6);
        jSlider_value.setMinimum(1);
        jSlider_value.setMinorTickSpacing(1);
        jSlider_value.setPaintLabels(true);
        jSlider_value.setPaintTicks(true);
        jSlider_value.setSnapToTicks(true);
        jSlider_value.setValue(1);

        jSpinner_antal_spillere.setModel(new javax.swing.SpinnerNumberModel(2, 2, 100, 1));
        jSpinner_antal_spillere.setValue(2);
        jSpinner_antal_spillere.setVerifyInputWhenFocusTarget(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Antal spillere");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Antal startterninger ");

        JLabel_Din_ip.setText("Din ip: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5))
                            .addComponent(jTextField_navn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(jButton_connect)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabel_Din_ip)
                            .addComponent(jButton_Opretserver))
                        .addGap(58, 362, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSpinner_antal_spillere, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jSlider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_connect)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_navn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSlider_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner_antal_spillere, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton_Opretserver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabel_Din_ip)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(120, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_connectActionPerformed
        
        validerPortogNavn();
        
        IP = jTextField_ip.getText();
        start = 1;
    }//GEN-LAST:event_jButton_connectActionPerformed

    private void jTextField_ipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ipActionPerformed

    private void jTextField_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_portActionPerformed

    private void jTextField_navnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_navnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_navnActionPerformed

    private void jButton_OpretserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OpretserverActionPerformed
        
        if(!server_started){
            // Lav en tråd som kører en Server med et spil.
            Thread t = new Thread(new Runnable() {
            public void run() {
                System.out.println(".run() er kaldt");
                String[] args = {""+jSpinner_antal_spillere.getValue(),""+jSlider_value.getValue(),""+jTextField_port.getText()};
                Server.ServerLogik.main(args);
                System.out.println(".run() er færdig");
            }
            });
            t.start();
           
            validerPortogNavn();

            IP = "127.0.0.1"; // Opret server på Localhost

            server_started = true; // Klient har startet en server
            start = 1; // Gå videre fra while loopet i main
        }

    }//GEN-LAST:event_jButton_OpretserverActionPerformed

    private void jTextField_portKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_portKeyTyped
        jTextField_portKeyPressed(evt);
    }//GEN-LAST:event_jTextField_portKeyTyped

    private void jTextField_portKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_portKeyPressed
        // Gør knapperne inaktive
        jButton_connect.setEnabled(false);
        jButton_Opretserver.setEnabled(false);
        
        // Gør dem aktive igen, når de overholder reglerne
        if(jTextField_port.getText().trim().matches("[0-9]+") && jTextField_port.getText().length() < 5 && jTextField_port.getText().length() > 3){ // Max port er "65535" så vi sætter et max på port 9999 og min på 1000
            jButton_connect.setEnabled(true);
            jButton_Opretserver.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField_portKeyPressed

    private void jTextField_portKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_portKeyReleased
        jTextField_portKeyPressed(evt);
    }//GEN-LAST:event_jTextField_portKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_Din_ip;
    public javax.swing.JButton jButton_Opretserver;
    private javax.swing.JButton jButton_connect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider_value;
    private javax.swing.JSpinner jSpinner_antal_spillere;
    private javax.swing.JTextField jTextField_ip;
    private javax.swing.JTextField jTextField_navn;
    private javax.swing.JTextField jTextField_port;
    // End of variables declaration//GEN-END:variables

    String getnavn() {
        return navn;
    }

    int getport() {
        return port;
    }

    String getIP() {
        return IP;
    }

    void resetstart() {
        start = 1;
    }

    /**
    * Tager den indskrevede port og navn fra tekstboksene og forsøger at validere dem. Hvis det ikke lykkes
      bliver navnet ændret til "Spillernavn".
    */
    private void validerPortogNavn() {
        
        /*Tag strengen og gør den til en int der kan være i port */
        String port_streng = jTextField_port.getText();
        port = 0;
        for (int i = 0; i < port_streng.length(); i++) {
            port += (port_streng.charAt(port_streng.length()-1-i)-48)*Math.pow(10, i);
        }
        
        /* Valider navnet */
        String navn_valid = jTextField_navn.getText();
        navn_valid = navn_valid.replaceAll("[^\\x00-\\xFF]", ""); // Frasorterer alle karaktere udover dem der er fra 00 til 255

        if(navn_valid.length() > MAX_NAME_LENGTH || navn_valid.trim().equals("")){ // Hvis navnet er for langt eller kun indeholder mellemrum
            navn = "Spillernavn";
        }else{ 
            navn = navn_valid;
        }
    }
}
