/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Klient;

import java.awt.Color;
import java.net.InetAddress;
import java.net.UnknownHostException;

/**
 *
 * @author chris
 */
public class Velkomstskærm extends javax.swing.JPanel {

    private KlientFunk klient;
    public int start = 0;
    private String navn;
    private int port;
    private String IP;
    public boolean server_started = false;
    private final short MAX_NAME_LENGTH = 38;

    /**
     * Creates new form Velkomstskærm
     */
    public Velkomstskærm() {
        initComponents();

        /**/
        String IP = "Kunne ikke få din IP";;
        try {
            IP = InetAddress.getLocalHost().getHostAddress();
            //JLabel_Din_ip.setForeground(Color.BLACK);
            //throw new UnknownHostException();
        } catch (UnknownHostException ex) {
            IP = "kunne ikke finde din IP-adresse";
            //JLabel_Din_ip.setForeground(Color.red);
        } finally {
            if (IP.matches("127.0.0.1")) {
                IP = "der er noget galt med dit netværksinterface. Tjek at du har internet!";
                //JLabel_Din_ip.setForeground(Color.red);
            }
            //JLabel_Din_ip.setText("Din IP-adresse: " + IP);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_ip = new javax.swing.JTextField();
        jButton_connect = new javax.swing.JButton();
        jTextField_port = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_playername = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_games = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        diceChoice = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpinner_playerNum = new javax.swing.JSpinner();
        JButton_create = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 500));

        jTextField_ip.setText("130.225.170.205");
        jTextField_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ipActionPerformed(evt);
            }
        });

        jButton_connect.setText("Forbind");
        jButton_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_connectActionPerformed(evt);
            }
        });

        jTextField_port.setText("?");
        jTextField_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_portActionPerformed(evt);
            }
        });
        jTextField_port.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_portKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_portKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_portKeyReleased(evt);
            }
        });

        jLabel2.setText("IP");

        jLabel3.setText("Port");

        jLabel5.setText("Spillernavn");

        jTextField_playername.setText("Navn");
        jTextField_playername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_playernameActionPerformed(evt);
            }
        });

        jTable_games.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Skaber", "Spillere", "Terninger", "Port"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_games);
        if (jTable_games.getColumnModel().getColumnCount() > 0) {
            jTable_games.getColumnModel().getColumn(0).setResizable(false);
            jTable_games.getColumnModel().getColumn(1).setResizable(false);
            jTable_games.getColumnModel().getColumn(2).setResizable(false);
            jTable_games.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Velkommen til terningespillet Snyd!");

        jTextField_username.setText("Navn");
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jLabel6.setText("Brugernavn");

        jLabel7.setText("Kode");

        jPasswordField_password.setText("jPasswordField1");

        diceChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        diceChoice.setSelectedIndex(5);
        diceChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceChoiceActionPerformed(evt);
            }
        });

        jLabel8.setText("Terninger");

        jLabel9.setText("Spillere");

        JButton_create.setText("Opret Server");
        JButton_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5)
                                .addGap(154, 154, 154))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_ip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField_playername, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jButton_connect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(diceChoice, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinner_playerNum)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addComponent(JButton_create)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JButton_create))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_connect)
                            .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_playername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diceChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner_playerNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(5, 5, 5)
                                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void diceChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diceChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diceChoiceActionPerformed

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jTextField_playernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_playernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_playernameActionPerformed

    private void jTextField_portKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_portKeyReleased
        jTextField_portKeyPressed(evt);
    }//GEN-LAST:event_jTextField_portKeyReleased

    private void jTextField_portKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_portKeyPressed
        // Gør knapperne inaktive
        jButton_connect.setEnabled(false);
        //jButton_Opretserver.setEnabled(false);

        // Gør dem aktive igen, når de overholder reglerne
        if (jTextField_port.getText().trim().matches("[0-9]+") && jTextField_port.getText().length() < 5 && jTextField_port.getText().length() > 3) { // Max port er "65535" så vi sætter et max på port 9999 og min på 1000
            jButton_connect.setEnabled(true);
            //jButton_Opretserver.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField_portKeyPressed

    private void jTextField_portKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_portKeyTyped
        jTextField_portKeyPressed(evt);
    }//GEN-LAST:event_jTextField_portKeyTyped

    private void jTextField_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_portActionPerformed

    private void jButton_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_connectActionPerformed

        validerPortogNavn();

        IP = jTextField_ip.getText();
        start = 1;
    }//GEN-LAST:event_jButton_connectActionPerformed

    private void jTextField_ipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ipActionPerformed

    private void JButton_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_createActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_createActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_create;
    private javax.swing.JComboBox<String> diceChoice;
    private javax.swing.JButton jButton_connect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_playerNum;
    private javax.swing.JTable jTable_games;
    private javax.swing.JTextField jTextField_ip;
    private javax.swing.JTextField jTextField_playername;
    private javax.swing.JTextField jTextField_port;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables

    String getnavn() {
        return navn;
    }

    int getport() {
        return port;
    }

    String getIP() {
        return IP;
    }

    void resetstart() {
        start = 1;
    }

    /**
     * Tager den indskrevede port og navn fra tekstboksene og forsøger at
     * validere dem. Hvis det ikke lykkes bliver navnet ændret til
     * "Spillernavn".
     */
    private void validerPortogNavn() {

        /*Tag strengen og gør den til en int der kan være i port */
        String port_streng = jTextField_port.getText();
        port = 0;
        for (int i = 0; i < port_streng.length(); i++) {
            port += (port_streng.charAt(port_streng.length() - 1 - i) - 48) * Math.pow(10, i);
        }

        /* Valider navnet */
        String navn_valid = jTextField_playername.getText();
        navn_valid = navn_valid.replaceAll("[^\\x00-\\xFF]", ""); // Frasorterer alle karaktere udover dem der er fra 00 til 255

        if (navn_valid.length() > MAX_NAME_LENGTH || navn_valid.trim().equals("")) { // Hvis navnet er for langt eller kun indeholder mellemrum
            navn = "Spillernavn";
        } else {
            navn = navn_valid;
        }
    }
}
