/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Klient;

/**
 *
 * @author chris
 */
public class Spil_skærm extends javax.swing.JPanel {

    /**
     * Creates new form Spil_skærm
     */
    public Spil_skærm() {
        initComponents();
    }
    /*
    public void paintComponent(Graphics g)
    {
            // Herunder referer g til et Graphics-objekt man kan tegne med
            super.paintComponent(g);                // tegn først baggrunden på panelet

            g.drawLine(0,0,xpos,ypos);

            g.fillOval(5,10,300,30);
            g.setColor(Color.GREEN);
            g.drawString(hilsen,100,30);

            System.out.println("Der blev tegnet!! "+xpos + ", "+ypos);
    }    
    */
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
